# Generated by Django 5.0.6 on 2024-06-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_modelparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelparameter',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csv_files/'),
        ),
    ]
