# Generated by Django 5.0.6 on 2024-06-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_modelparameter_csv_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
