# Generated by Django 5.0.6 on 2024-06-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_modelparameter_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=50)),
                ('target', models.TextField()),
                ('result', models.TextField(null=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='csv_files/')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ModelParameter',
        ),
    ]
